config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'pages/contato'

  resources :comentarios
  resources :livros
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comentario.rb
class Comentario < ApplicationRecord
  belongs_to :user
  belongs_to :livro
end

app/models/livro.rb
class Livro < ApplicationRecord
  belongs_to :user
  has_one_attached :imagem
  has_many :comentarios
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :image
  has_many :livros
  has_many :comentarios
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comentarios_controller.rb
class ComentariosController < ApplicationController
  before_action :set_comentario, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /comentarios or /comentarios.json
  def index
    @comentarios = Comentario.all
  end

  # GET /comentarios/1 or /comentarios/1.json
  def show
  end

  # GET /comentarios/new
  def new
    @comentario = current_user.comentarios.new(livro_id: params[:livro_id])
  end
  

  # GET /comentarios/1/edit
  def edit
  end

  # POST /comentarios or /comentarios.json
  def create
    @comentario = Comentario.new(comentario_params)

    respond_to do |format|
      if @comentario.save
        format.html { redirect_to @comentario, notice: "Comentario was successfully created." }
        format.json { render :show, status: :created, location: @comentario }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comentario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comentarios/1 or /comentarios/1.json
  def update
    respond_to do |format|
      if @comentario.update(comentario_params)
        format.html { redirect_to @comentario, notice: "Comentario was successfully updated." }
        format.json { render :show, status: :ok, location: @comentario }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comentario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comentarios/1 or /comentarios/1.json
  def destroy
    @comentario.destroy
    respond_to do |format|
      format.html { redirect_to comentarios_url, notice: "Comentario was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comentario
      @comentario = Comentario.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comentario_params
      params.require(:comentario).permit(:conteudo, :user_id, :livro_id)
    end
end

app/controllers/livros_controller.rb
class LivrosController < ApplicationController
  before_action :set_livro, only: %i[ show edit update destroy ]

  # GET /livros or /livros.json
  def index
    @livros = Livro.all
  end

  # GET /livros/1 or /livros/1.json
  def show
    @comentarios = Comentario.all.where(livro: params[:id])
  end
  

  # GET /livros/new
  def new
    @livro = current_user.livros.new
  end  

  # GET /livros/1/edit
  def edit
  end

  # POST /livros or /livros.json
  def create
    @livro = Livro.new(livro_params)

    respond_to do |format|
      if @livro.save
        format.html { redirect_to @livro, notice: "Livro was successfully created." }
        format.json { render :show, status: :created, location: @livro }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @livro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /livros/1 or /livros/1.json
  def update
    respond_to do |format|
      if @livro.update(livro_params)
        format.html { redirect_to @livro, notice: "Livro was successfully updated." }
        format.json { render :show, status: :ok, location: @livro }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @livro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /livros/1 or /livros/1.json
  def destroy
    @livro.destroy
    respond_to do |format|
      format.html { redirect_to livros_url, notice: "Livro was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_livro
      @livro = Livro.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def livro_params
      params.require(:livro).permit(:titulo, :autor, :sinopse, :publicado, :user_id, :imagem)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def contato
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comentarios_helper.rb
module ComentariosHelper
end

app/helpers/livros_helper.rb
module LivrosHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/comentarios/_form.html.erb
<%= form_with(model: comentario) do |form| %>
  <% if comentario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comentario.errors.count, "error") %> prohibited this comentario from being saved:</h2>

      <ul>
        <% comentario.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :conteudo %>
    <%= form.text_area :conteudo %>
  </div>

  <%= form.hidden_field :user_id %>

  <%= form.hidden_field :livro_id %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comentarios/edit.html.erb
<h1>Editing Comentario</h1>

<%= render 'form', comentario: @comentario %>

<%= link_to 'Show', @comentario %> |
<%= link_to 'Back', comentarios_path %>

app/views/comentarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comentarios</h1>

<table>
  <thead>
    <tr>
      <th>Conteudo</th>
      <th>User</th>
      <th>Livro</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comentarios.each do |comentario| %>
      <tr>
        <td><%= comentario.conteudo %></td>
        <td><%= comentario.user_id %></td>
        <td><%= comentario.livro_id %></td>
        <td><%= link_to 'Show', comentario %></td>
        <td><%= link_to 'Edit', edit_comentario_path(comentario) %></td>
        <td><%= link_to 'Destroy', comentario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comentario', new_comentario_path %>

app/views/comentarios/new.html.erb
<h1>New Comentario</h1>

<%= render 'form', comentario: @comentario %>

<%= link_to 'Back', comentarios_path %>

app/views/comentarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Conteudo:</strong>
  <%= @comentario.conteudo %>
</p>

<p>
  <strong>User:</strong>
  <%= @comentario.user.email %>
</p>

<p>
  <strong>Livro:</strong>
  <%= @comentario.livro.titulo %>
</p>

<%= link_to 'Back', livros_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookstore</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'pages/navbar' %>

    <%= render 'pages/flash' %>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/livros/_form.html.erb
<%= form_with(model: livro) do |form| %>
  <% if livro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(livro.errors.count, "error") %> prohibited this livro from being saved:</h2>

      <ul>
        <% livro.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :titulo %>
    <%= form.text_field :titulo %>
  </div>

  <div class="field">
    <%= form.label :autor %>
    <%= form.text_field :autor %>
  </div>

  <div class="field">
    <%= form.label :imagem %>
    <%= form.file_field :imagem %>
  </div>

  <div class="field">
    <%= form.label :sinopse %>
    <%= form.text_area :sinopse %>
  </div>

  <div class="field"> 
    <%= form.label :publicado %>
    <%= form.date_select :publicado, :start_year => 1455, :end_year => Time.now.year + 10 %>
  </div>

  <%= form.hidden_field :user_id %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/livros/edit.html.erb
<h1>Editing Livro</h1>

<%= render 'form', livro: @livro %>

<%= link_to 'Show', @livro %> |
<%= link_to 'Back', livros_path %>

app/views/livros/index.html.erb
<h1>Livros</h1>

<% if user_signed_in? %>
  <%= link_to "Cadastrar um novo livro", new_livro_path, class:"btn btn-primary"%>
<% end %>

<hr>

<div class="grid">
  <% @livros.each do |livro| %>
    <div class="card">
      <center><h5 class="card-header"><%= livro.titulo %></h5></center>
      <%= image_tag(livro.imagem, class:"card-img-top") %>
      <center><h6 style="margin-top: 10px">@<%= livro.user.username %></h6></center>
      <div class="card-body">
        <h5 class="card-title"><%= livro.autor %></h5>
        <h6 class="card-subtitle mb-2 text-muted">Publicado em: <td><%= livro.publicado.strftime("%d/%m/%y") %></td></h6>
        <p class="card-text"><%= livro.sinopse %></p>
        <% if livro.user == current_user %>
          <td><%= link_to 'Editar', edit_livro_path(livro), class:"btn btn-success" %></td>
          <td><%= link_to 'Deletar', livro, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %></td>
        <% end %>
      </div>
    </div>
  <% end %>
</div>
</div>

app/views/livros/new.html.erb
<h1>New Livro</h1>

<%= render 'form', livro: @livro %>

<%= link_to 'Back', livros_path %>

app/views/livros/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @livro.titulo %>
</p>

<p>
  <strong>Autor:</strong>
  <%= @livro.autor %>
</p>

<div>
  <%= image_tag(@livro.imagem) %>
</div>

<p>
  <strong>Sinopse:</strong>
  <%= @livro.sinopse %>
</p>

<p>
  <strong>Publicado:</strong>
  <%= @livro.publicado %>
</p>

<p>
  <strong>User:</strong>
  <%= @livro.user_id %>
</p>

<% if @livro.user == current_user %>
  <%= link_to 'Edit', edit_livro_path(@livro) %> |
<% end %>
<%= link_to 'Back', livros_path %>
  
<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Conteudo</th>
    </tr>
  </thead>
  
  <tbody>
    <% @comentarios.each do |comentario| %>
      <tr>
        <td><%= comentario.user.email %></td>
        <td><%= comentario.conteudo %></td>
      </tr>
    <% end %>
  </tbody>
</table>
  
<% if user_signed_in? %>
  <%# o link do novo comentário é passado com um parâmetro que leva o id do livro a ser comentado %>
  <%= link_to 'New Comentario', new_comentario_path(livro_id: @livro.id)%> 
<% end %>

app/views/pages/_flash.html.erb
<% flash.each do |notice, message| %>
    <%= content_tag(:div, message, class:"alert alert-info #{notice}") %>
<% end %>

app/views/pages/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <%= link_to "BookStore", root_path, class: "navbar-brand" %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse navbar-links" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <%= link_to "Livros", livros_path, class:"nav-link" %>
                </li>
                <li class="nav-item">
                    <%= link_to "Contato", pages_contato_path, class:"nav-link" %>
                </li>
            </ul>

            <ul class="navbar-nav navbar-buttons">
                <% if user_signed_in? %>
                    <li class="nav-item">
                        <%= link_to "Editar Perfil", edit_user_registration_path, class:"btn btn-primary" %>
                    </li>
                    <li class="nav-item">
                        <%= link_to "Sair", destroy_user_session_path, method: :delete, class:"btn btn-danger" %>
                    </li>
                <% else %>
                    <li class="nav-item">
                        <%= link_to "Cadastrar", new_user_registration_path, class:"btn btn-success" %>
                    </li>
                    <li class="nav-item">
                        <%= link_to "Login", new_user_session_path, class:"btn btn-primary" %>
                    </li>
                <% end %>
            </ul>
        </div>
    </div>
</nav>